# 텐서플로우 2.0에서 1.x.x버전을 사용하기 위한 코드

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [13]:
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


In [14]:
print(tf.__version__)

2.0.0


# 텐서플로우 모델 초기기화

In [15]:
model = tf.global_variables_initializer()

In [86]:
data = pd.read_csv("data.csv", encoding="euc-KR")

In [87]:
print(data.head())

           날짜  평균 풍속  최저 기온  최고 기온  강수량  평균 가격
0  2010-01-01    1.2  -11.0    0.9  0.0   2123
1  2010-01-02    0.9   -5.5    5.5  0.8   2123
2  2010-01-03    1.8   -6.9    1.4  0.0   2123
3  2010-01-04    2.3   -5.1    2.2  5.9   2020
4  2010-01-05    2.2   -8.7   -1.8  0.7   2060


In [88]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [89]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2922 entries, 0 to 2921
Data columns (total 6 columns):
날짜       2922 non-null object
평균 풍속    2922 non-null float64
최저 기온    2922 non-null float64
최고 기온    2922 non-null float64
강수량      2922 non-null float64
평균 가격    2922 non-null int64
dtypes: float64(4), int64(1), object(1)
memory usage: 137.1+ KB


In [90]:
data.describe()

평균 풍속        최저 기온        최고 기온          강수량         평균 가격
count  2922.000000  2922.000000  2922.000000  2922.000000   2922.000000
mean      1.501540     8.288227    18.378645     3.445140   3276.506502
std       0.765881    10.232362     9.803192     8.563899   1369.364603
min       0.000000   -14.800000    -7.400000     0.000000   1093.000000
25%       1.000000    -0.700000     9.700000     0.000000   2292.000000
50%       1.300000     8.700000    19.950000     0.100000   3026.000000
75%       1.900000    17.575000    27.100000     2.175000   3974.000000
max       6.200000    25.900000    35.600000    95.500000  12410.000000

In [91]:
data.head()

날짜  평균 풍속  최저 기온  최고 기온  강수량  평균 가격
0  2010-01-01    1.2  -11.0    0.9  0.0   2123
1  2010-01-02    0.9   -5.5    5.5  0.8   2123
2  2010-01-03    1.8   -6.9    1.4  0.0   2123
3  2010-01-04    2.3   -5.1    2.2  5.9   2020
4  2010-01-05    2.2   -8.7   -1.8  0.7   2060

## 데이터프레임에서 특수문자 제거 후 자료형 변경
- 2020-03-01에서 -를 제거하고 int형으로 변환

In [92]:
data['날짜']=data['날짜'].str.replace('-','').astype(int)

In [93]:
data.head()

날짜  평균 풍속  최저 기온  최고 기온  강수량  평균 가격
0  20100101    1.2  -11.0    0.9  0.0   2123
1  20100102    0.9   -5.5    5.5  0.8   2123
2  20100103    1.8   -6.9    1.4  0.0   2123
3  20100104    2.3   -5.1    2.2  5.9   2020
4  20100105    2.2   -8.7   -1.8  0.7   2060

In [94]:
xy = np.array(data, dtype=np.float32)

In [96]:
xy

array([[ 2.0100100e+07,  1.2000000e+00, -1.1000000e+01,  8.9999998e-01,
         0.0000000e+00,  2.1230000e+03],
       [ 2.0100102e+07,  8.9999998e-01, -5.5000000e+00,  5.5000000e+00,
         8.0000001e-01,  2.1230000e+03],
       [ 2.0100104e+07,  1.8000000e+00, -6.9000001e+00,  1.4000000e+00,
         0.0000000e+00,  2.1230000e+03],
       ...,
       [ 2.0171228e+07,  8.0000001e-01, -2.0999999e+00,  8.0000000e+00,
         0.0000000e+00,  2.9010000e+03],
       [ 2.0171230e+07,  2.5999999e+00, -1.6000000e+00,  7.0999999e+00,
         6.0000002e-01,  2.9010000e+03],
       [ 2.0171232e+07,  2.5000000e+00, -2.0000000e+00,  5.8000002e+00,
         4.0000001e-01,  2.9010000e+03]], dtype=float32)

In [97]:
type(xy)

numpy.ndarray

In [99]:
xy[0, 1]

1.2

## xy 데이터에서 x 변수는 평균풍속, 최저기온, 최고기온, 강수량 가져오기

In [104]:
x_data = xy[:, 1:-1]

In [105]:
x_data

array([[  1.2, -11. ,   0.9,   0. ],
       [  0.9,  -5.5,   5.5,   0.8],
       [  1.8,  -6.9,   1.4,   0. ],
       ...,
       [  0.8,  -2.1,   8. ,   0. ],
       [  2.6,  -1.6,   7.1,   0.6],
       [  2.5,  -2. ,   5.8,   0.4]], dtype=float32)

In [109]:
y_data =xy[:, [-1]]

In [110]:
y_data

array([[2123.],
       [2123.],
       [2123.],
       ...,
       [2901.],
       [2901.],
       [2901.]], dtype=float32)

In [118]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [120]:
hypothesis = tf.matmul(X, W) + b

In [121]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [122]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.000005)
train = optimizer.minimize(cost)

In [123]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [127]:
for step in range(100001):
    cost_, hypo_, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 ==0:
        print("#", step, "손실비용: ", cost_)
        print("- 배추가격: ", hypo_[1])

# 0 손실비용:  2166828.2
- 배추가격:  [2544.8564]
# 500 손실비용:  2166566.5
- 배추가격:  [2544.679]
# 1000 손실비용:  2166305.8
- 배추가격:  [2544.5146]
# 1500 손실비용:  2166045.0
- 배추가격:  [2544.3486]
# 2000 손실비용:  2165786.5
- 배추가격:  [2544.18]
# 2500 손실비용:  2165528.2
- 배추가격:  [2544.0117]
# 3000 손실비용:  2165271.2
- 배추가격:  [2543.843]
# 3500 손실비용:  2165014.0
- 배추가격:  [2543.6724]
# 4000 손실비용:  2164759.2
- 배추가격:  [2543.4993]
# 4500 손실비용:  2164504.0
- 배추가격:  [2543.3264]
# 5000 손실비용:  2164249.5
- 배추가격:  [2543.1536]
# 5500 손실비용:  2163997.0
- 배추가격:  [2542.978]
# 6000 손실비용:  2163744.8
- 배추가격:  [2542.8008]
# 6500 손실비용:  2163492.5
- 배추가격:  [2542.6238]
# 7000 손실비용:  2163241.8
- 배추가격:  [2542.4468]
# 7500 손실비용:  2162991.5
- 배추가격:  [2542.3103]
# 8000 손실비용:  2162743.0
- 배추가격:  [2542.1765]
# 8500 손실비용:  2162495.2
- 배추가격:  [2542.043]
# 9000 손실비용:  2162249.0
- 배추가격:  [2541.905]
# 9500 손실비용:  2162004.2
- 배추가격:  [2541.761]
# 10000 손실비용:  2161760.5
- 배추가격:  [2541.6145]
# 10500 손실비용:  2161517.5
- 배추가격:  [2541.468]
# 11000 손실비용:  216127

# 90000 손실비용:  2130608.5
- 배추가격:  [2527.3372]
# 90500 손실비용:  2130447.2
- 배추가격:  [2527.282]
# 91000 손실비용:  2130287.0
- 배추가격:  [2527.2344]
# 91500 손실비용:  2130126.5
- 배추가격:  [2527.2124]
# 92000 손실비용:  2129966.8
- 배추가격:  [2527.1902]
# 92500 손실비용:  2129806.5
- 배추가격:  [2527.1682]
# 93000 손실비용:  2129648.5
- 배추가격:  [2527.1404]
# 93500 손실비용:  2129492.0
- 배추가격:  [2527.1064]
# 94000 손실비용:  2129336.2
- 배추가격:  [2527.0728]
# 94500 손실비용:  2129180.5
- 배추가격:  [2527.039]
# 95000 손실비용:  2129024.8
- 배추가격:  [2527.0054]
# 95500 손실비용:  2128869.2
- 배추가격:  [2526.9712]
# 96000 손실비용:  2128713.8
- 배추가격:  [2526.9375]
# 96500 손실비용:  2128558.8
- 배추가격:  [2526.9036]
# 97000 손실비용:  2128403.8
- 배추가격:  [2526.8662]
# 97500 손실비용:  2128250.0
- 배추가격:  [2526.8237]
# 98000 손실비용:  2128096.8
- 배추가격:  [2526.7815]
# 98500 손실비용:  2127943.8
- 배추가격:  [2526.739]
# 99000 손실비용:  2127790.0
- 배추가격:  [2526.6963]
# 99500 손실비용:  2127636.8
- 배추가격:  [2526.6538]
# 100000 손실비용:  2127483.5
- 배추가격:  [2526.6113]


In [131]:
saver = tf.train.Saver()
save_path = saver.save(sess, "./saved.cpkt")
print("학습된 모델을 저장했습니다")

학습된 모델을 저장했습니다
